import { computed, ref, watch } from 'vue'
import { defineStore } from 'pinia'

const english = {
  jumpDate: 'Jump to date',
  hideProgramme: 'Hide programme',
  showProgramme: 'Show programme',
  allHidden: 'All programmes are hidden.',
  showAll: 'Show all programmes',
  changes: 'Timetable changes',
  changesHelp:
    'Latest detected changes compared with the previous successful load. Refresh to check for updates.',
  dismiss: 'Dismiss changes',
  added: 'Added',
  removed: 'Removed',
  changed: 'Updated',
  roomChanged: 'Room changed',
  timeChanged: 'Time changed',
  before: 'Before',
  after: 'Now',
  dailySummary: 'Daily summary',
  finishes: 'Finishes at',
  classTime: 'Class time',
  breaks: 'Breaks between classes',
  noBreaks: 'No breaks between classes',
  programme: 'Study programme',
  programmes: 'Study programmes',
  selectProgrammes: 'Select study programmes',
  selectionHelp: 'Select one or more programmes to combine their timetables.',
  showTimetables: 'Show timetables',
  selectedProgrammes: 'Selected programmes',
  removeProgramme: 'Remove programme',
  overlap: 'Overlapping classes',
  overlapsWith: 'Overlaps with',
  incompleteTimetable: 'Some programmes could not be loaded',
  groupPerProgramme: 'Choose your group for each programme',
  selectProgramme: 'Select Study Programme',
  activeProgramme: 'Active programme',
  searchLabel: 'Search for your study programme or year',
  searchPlaceholder: 'Search study programme…',
  clearSearch: 'Clear search',
  selected: 'Selected',
  noResults: 'No programmes match your search.',
  choosePrompt: 'Choose your study programme to see your timetable.',
  loadingProgrammes: 'Loading study programmes…',
  loading: 'Loading your timetable…',
  loadError: 'Unable to load the timetable.',
  programmesError: 'Unable to load study programmes.',
  errorHelp: 'Check your connection and try again.',
  retry: 'Try again',
  empty: 'No events scheduled for this day',
  emptyHelp: 'Enjoy the break, or choose another date.',
  noProgrammes: 'No study programmes are available yet.',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  today: 'Today',
  thisWeek: 'This week',
  previous: 'Previous',
  next: 'Next',
  back: 'Back',
  backWeek: 'Back to Week',
  backMonth: 'Back to Month',
  allGroups: 'All groups',
  group: 'Group',
  filter: 'Filter',
  dimmedHelp: 'Other groups shown dimmed',
  reset: 'Reset',
  yourGroup: 'Your group',
  dimmed: 'Other group',
  collapseAll: 'Collapse all',
  expandAll: 'Expand all',
  events: 'events',
  openDay: 'Open day view',
  lecture: 'Lecture',
  lab: 'Lab / Tutorial',
  eLecture: 'Remote lecture',
  eLab: 'Remote lab',
  exam: 'Midterm / Exam',
  other: 'Other',
  legend: 'Event legend',
  currentClass: 'Current class',
  remaining: 'Remaining',
  minutes: 'min',
  synced: 'ICS synchronized',
  refresh: 'Refresh timetable',
  darkMode: 'Switch to dark mode',
  lightMode: 'Switch to light mode',
  navigation: 'Schedule navigation',
  weekNumber: 'Week',
  duration: 'Duration',
  nextClass: 'Next class',
  startsIn: 'Starts in',
  noNextClass: 'No upcoming classes in this timetable',
  hideGroups: 'Hide other groups',
  hiddenHelp: 'Other groups hidden',
  savedSchedule: 'Showing saved timetable',
  lastUpdated: 'Last updated',
  savedHelp: 'Changes may not be reflected until you reconnect.',
  saveFailed: 'Offline saving is unavailable on this device.',
  refreshing: 'Refreshing…',
  swipeHint: 'Swipe left or right to change dates',
} as const
const slovenian: Record<keyof typeof english, string> = {
  jumpDate: 'Skoči na datum',
  hideProgramme: 'Skrij program',
  showProgramme: 'Prikaži program',
  allHidden: 'Vsi programi so skriti.',
  showAll: 'Prikaži vse programe',
  changes: 'Spremembe urnika',
  changesHelp:
    'Zadnje zaznane spremembe glede na prejšnje uspešno nalaganje. Osvežite za nove podatke.',
  dismiss: 'Opusti spremembe',
  added: 'Dodano',
  removed: 'Odstranjeno',
  changed: 'Posodobljeno',
  roomChanged: 'Spremenjena učilnica',
  timeChanged: 'Spremenjen čas',
  before: 'Prej',
  after: 'Zdaj',
  dailySummary: 'Dnevni povzetek',
  finishes: 'Konec ob',
  classTime: 'Čas pouka',
  breaks: 'Odmori med dogodki',
  noBreaks: 'Ni odmorov med dogodki',
  programme: 'Študijski program',
  programmes: 'Študijski programi',
  selectProgrammes: 'Izberite študijske programe',
  selectionHelp: 'Izberite enega ali več programov za skupni prikaz urnikov.',
  showTimetables: 'Prikaži urnike',
  selectedProgrammes: 'Izbrani programi',
  removeProgramme: 'Odstrani program',
  overlap: 'Prekrivanje dogodkov',
  overlapsWith: 'Prekriva se z',
  incompleteTimetable: 'Nekaterih programov ni bilo mogoče naložiti',
  groupPerProgramme: 'Izberite svojo skupino za vsak program',
  selectProgramme: 'Izberite študijski program',
  activeProgramme: 'Aktivni program',
  searchLabel: 'Poiščite svoj študijski program ali letnik',
  searchPlaceholder: 'Poiščite študijski program…',
  clearSearch: 'Počisti iskanje',
  selected: 'Izbrano',
  noResults: 'Noben program ne ustreza iskanju.',
  choosePrompt: 'Izberite študijski program za prikaz urnika.',
  loadingProgrammes: 'Nalaganje študijskih programov…',
  loading: 'Nalaganje urnika…',
  loadError: 'Urnika ni mogoče naložiti.',
  programmesError: 'Študijskih programov ni mogoče naložiti.',
  errorHelp: 'Preverite povezavo in poskusite znova.',
  retry: 'Poskusi znova',
  empty: 'Za ta dan ni dogodkov',
  emptyHelp: 'Uživajte v prostem času ali izberite drug datum.',
  noProgrammes: 'Študijski programi še niso na voljo.',
  day: 'Dan',
  week: 'Teden',
  month: 'Mesec',
  daily: 'Dnevno',
  weekly: 'Tedensko',
  monthly: 'Mesečno',
  today: 'Danes',
  thisWeek: 'Ta teden',
  previous: 'Prejšnji',
  next: 'Naslednji',
  back: 'Nazaj',
  backWeek: 'Nazaj na teden',
  backMonth: 'Nazaj na mesec',
  allGroups: 'Vse skupine',
  group: 'Skupina',
  filter: 'Filter',
  dimmedHelp: 'Druge skupine so zatemnjene',
  reset: 'Ponastavi',
  yourGroup: 'Vaša skupina',
  dimmed: 'Druga skupina',
  collapseAll: 'Strni vse',
  expandAll: 'Razširi vse',
  events: 'dogodkov',
  openDay: 'Odpri dnevni pogled',
  lecture: 'Predavanje',
  lab: 'Vaje',
  eLecture: 'e-Predavanje',
  eLab: 'e-Vaje',
  exam: 'Izpit / Kolokvij',
  other: 'Drugo',
  legend: 'Legenda dogodkov',
  currentClass: 'Trenutno na urniku',
  remaining: 'Preostanek',
  minutes: 'min',
  synced: 'ICS sinhroniziran',
  refresh: 'Osveži urnik',
  darkMode: 'Preklopi na temni način',
  lightMode: 'Preklopi na svetli način',
  navigation: 'Navigacija urnika',
  weekNumber: 'Teden',
  duration: 'Trajanje',
  nextClass: 'Naslednje predavanje ali vaje',
  startsIn: 'Začetek čez',
  noNextClass: 'V tem urniku ni prihodnjih dogodkov',
  hideGroups: 'Skrij druge skupine',
  hiddenHelp: 'Druge skupine so skrite',
  savedSchedule: 'Prikazan je shranjeni urnik',
  lastUpdated: 'Nazadnje posodobljeno',
  savedHelp: 'Spremembe bodo vidne po ponovni vzpostavitvi povezave.',
  saveFailed: 'Shranjevanje za uporabo brez povezave v tej napravi ni na voljo.',
  refreshing: 'Osveževanje…',
  swipeHint: 'Za spremembo datuma podrsajte levo ali desno',
}

export const useLanguageStore = defineStore('language', () => {
  const language = ref<'en' | 'sl'>(
    localStorage.getItem('um-calendar-language') === 'sl' ? 'sl' : 'en',
  )
  const locale = computed(() => (language.value === 'sl' ? 'sl-SI' : 'en-GB'))
  watch(
    language,
    (value) => {
      localStorage.setItem('um-calendar-language', value)
      document.documentElement.lang = value
    },
    { immediate: true },
  )
  function t(key: keyof typeof english): string {
    return (language.value === 'sl' ? slovenian : english)[key]
  }
  function date(value: Date, options: Intl.DateTimeFormatOptions = { dateStyle: 'full' }) {
    return new Intl.DateTimeFormat(locale.value, options).format(value)
  }
  function time(value: Date) {
    return date(value, { hour: '2-digit', minute: '2-digit', hour12: false })
  }
  return { language, locale, t, date, time }
})
